batch_size: 32
dropout: 0.1
embed_size: 128
gradient_clip_val: 0.16803154203784526
hidden_size: 224
learning_rate: 0.00042631974982415284
num_layers: 4
weight_decay: 3.0119425325804118e-05


TODO: Analyze my_study.db with optuna's dashboard
TODO: Try the new params on the model